name:
  CI
on: 
  pull_request:
    branches: [main]

jobs:
  build-with-gradle:
    runs-on: ubuntu-20.04
    steps:
    - name: 브랜치로 이동
      uses: actions/checkout@v3
    - name: JDK 17 설치
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'zulu'
    - name: application.yml 생성
      run: |
        mkdir src/main/resources
        touch src/main/resources/application.yml
        echo "${{ secrets.APPLICATION_YML }}" > src/main/resources/application.yml
    - name: gradlew에 실행 권한 부여
      run: chmod +x gradlew
      
    - name: 프로젝트 빌드
      run: ./gradlew build -x test
